#%RAML 1.0 DataType

type: string
description: |
  Token used for the account authentication.

  This token is used for the Merchant's identification and authentication and should be kept secret at all times.
  In a standard implementation, this is the only externally available data allowing to access the Merchant's account resources.
example: "025f87e546becfa77cf04d3906f703524d5f17e24c2dca8afbb0281ca98b5124d8"
