#%RAML 1.0 DataType

type: string
description: |
  Token used for the account authentication.
  This token is used for the Merchant's identification and authentication and should be kept secret at all times.
  In a standard implementation, this is the only externally available data allowing to access the Merchant's account resources.
example: "1p2o3i4u5y6t7r8e9w0q"
