#%RAML 1.0 DataType

type: string
description: |
  The domain name of the Merchant's service.

  If ***domain*** will be different than the ***return_url***'s domain then Merchant's account should be displayed as not verified in the Wallet.
minLength: 4
maxLength: 128
example: my.site.url
