#%RAML 1.0 DataType

type: string
default: "eu.carrotpay.com"
description: |
  A default Issuer to use for all transactions.
  If it's not explicitly set by the Merchant then the default Gateway's Issuer is used.
example: "eu.carrotpay.com"
