#%RAML 1.0 DataType

type: string
minLength: 1
maxLength: 128
description: |
  Short information from the Merchant to be presented to the Buyer e.g. a thank you note, confirmation of purchase.
  This may be useful especially if there is no need for extra steps after payment is done i.e. by passing ***return_url***.
  On occasions such as payment for a subscription, the Merchant may simply wish to confirm that a payment has been received without providing a separate confirmation or download page. A notification may be used in such a situation.

  Notification should be recorded in the history of the Buyer's Wallet.
example: Thank you for your payment. Your subscription is now active.
