#%RAML 1.0 DataType

type: string
enum:
  - ok
  - payment-unknown
  - after-expires
  - insufficient-amount
  - bad-coins
  - retry-expired
description: Payment status indicator described in the Payment specification document.
