#%RAML 1.0 DataType

type: boolean
default: false
description: Indicates if the Gateway is offering an option to send a refund email containing new Coins resulting from a failed verification attempt at its Issuer.
