#%RAML 1.0 DataType

type: string
minLength: 0
maxLength: 256
description: |
  An URL where the purchased product may be obtained and/or order finalised.
  'transaction_id' and 'order_id' (if given) will be appended to this URL, e.g. 'return_url' such as "https://my.site.url/pay?in=12345" will became "https://my.site.url/pay?in=12345&transaction_id=98765&order_id=98765" .

  If 'return_url' is not set then default value from the account's settings is taken - if set.

  In general it is a good practice to provide a 'return_url'.
example: https://my.site.url/pay?in=12345

