#%RAML 1.0 DataType

type: object
description: |
  An object containing information about refund receiver.
properties:
  email:
    type: !include Email.raml
    required: true
    description: An email address where a payment refund should be sent.
  password:
    type: !include Password.raml
    required: false
    description: A string the Merchant MUST use to encrypt Coins with before sending them through email.
  reference:
    type: string
    required: false
    description: If the ***reference*** element is present it should be echoed in the ***reference*** element of the refund file.
