#%RAML 1.0 DataType

type: number
description: |
  The minimum number of seconds that a Wallet should wait before deciding that a call to ***payment_url*** has failed.
example: 60
default: 60
minimum: 5
maximum: 300
