#%RAML 1.0 DataType

type: string
enum:
  - payment
  - blockchain-transfer
  - coin-file-transfer
description: Type of transaction defining the internal representation of the transaction's object and its capabilities.
example: payment
