#%RAML 1.0 DataType

properties:
  default_payment_currency?: !include primitives/DefaultPaymentCurrency.raml
  default_payment_timeout?: !include primitives/DefaultPaymentTimeout.raml
  provide_receipt_via_email?: !include primitives/ProvideReceiptViaEmail.raml
  provide_refund_via_email?: !include primitives/ProvideRefundViaEmail.raml
  home_issuer?: !include primitives/HomeIssuer.raml
