#%RAML 1.0 DataType

displayName: Update Account
properties:
  domain?: !include primitives/Domain.raml
  email_account_contact?: !include primitives/EmailAccountContact.raml
  email_customer_contact?: !include primitives/EmailCustomerContact.raml
  name?: !include primitives/Name.raml
example: !include ../examples/AccountCore.json
