#%RAML 1.0 DataType

uses:
  types: primitives/ValueTypesLib.raml

type: !include TransactionCore.raml
properties:
  currency:
    type: !include primitives/Currency.raml
    required: true
    description: Currency of _Coins_ to be transfered.
  value:
    type: types.ValueMulti
    required: true
    description: |
      Value of _Coins_ to be transfered.

      If ***value*** is explicitly set to ***all*** then all funds of a given currency will be transfered.
  description:
    type: !include primitives/Description.raml
    required: false
    description: A short description that is meaningful to the Merchant. This description will be recorded in the transactions' history.
