#%RAML 1.0 DataType

type: !include TransactionTransferCore.raml
properties:
  speed?: !include primitives/Speed.raml
  address: !include primitives/BlockchainAddress.raml
  label?: !include primitives/Label.raml
example: !include ../examples/TransactionTransferBlockchainRequest.json
